apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-replicaset
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          envFrom:
            - configMapRef:
                name: portal-noticias
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias