micronaut:
  application:
    name: casaDoCodigo

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/casa-do-codigo
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
