version: '3'
services:

  postgres:
    image: 'postgres:9.6-alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: casa-do-codigo
      POSTGRES_HOST: postgres

  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - 4242:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres-volume:
  postgres-transacao: